// One-off extraction: pulls TRIPS, SLOTS, and HOMES verbatim out of
// reference-v1-app.html and writes them as typed TS modules in src/data/.
// Never edits reference-v1-app.html. Safe to re-run any time v1 changes.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const html = readFileSync(path.join(root, "reference-v1-app.html"), "utf8");

function extractValue(startMarker, endMarker, prefixToStrip) {
  const startIdx = html.indexOf(startMarker);
  if (startIdx === -1) throw new Error(`start marker not found: ${startMarker}`);
  const endIdx = html.indexOf(endMarker, startIdx);
  if (endIdx === -1) throw new Error(`end marker not found: ${endMarker}`);
  let slice = html.slice(startIdx, endIdx);
  slice = slice.slice(prefixToStrip.length).trim();
  if (slice.endsWith(";")) slice = slice.slice(0, -1).trim();
  return new Function(`"use strict"; return (${slice});`)();
}

const TRIPS = extractValue(
  "const TRIPS=[",
  "/* ============ CALENDAR SLOTS",
  "const TRIPS="
);

// Phase 7 Part A: merge in hand-authored activity expansions (15-25 per
// city, replacing v1's original 3-7) for whichever trips have one so far --
// see src/data/activityExpansions.json and CLAUDE.md's Phase 7 section for
// how this gets extended over future sessions. reference-v1-app.html itself
// is never touched; trips with no overlay entry yet just keep their
// original extracted `a` array.
const activityExpansionsPath = path.join(root, "src/data/activityExpansions.json");
const activityExpansions = JSON.parse(readFileSync(activityExpansionsPath, "utf8"));
let expanded = 0;
for (const t of TRIPS) {
  if (activityExpansions[t.id]) {
    t.a = activityExpansions[t.id];
    expanded++;
  }
}
const SLOTS = extractValue(
  "const SLOTS=[",
  "const TRIP=Object.fromEntries",
  "const SLOTS="
);
const HOMES = extractValue("const HOMES={", "let HOME=", "const HOMES=");

if (TRIPS.length !== 212) {
  throw new Error(`expected 212 trips, got ${TRIPS.length}`);
}

const TRIP_TYPE = `export interface Trip {
  id: string;
  n: string;
  c: string;
  reg: string;
  co: [number, number];
  t: string[];
  cats: string[];
  m: number[];
  g: number;
  ci: number;
  wx: string;
  w: string;
  a: [string, number][];
  f: [string, number][];
}

export const TRIPS: Trip[] = `;

const SLOT_TYPE = `export type SlotKind = "weekend" | "special" | "break" | "post";

export interface Slot {
  id: string;
  label: string;
  date: string;
  s: [number, number];
  e: [number, number];
  kind: SlotKind;
  note?: string;
}

export const SLOTS: Slot[] = `;

const HOMES_TYPE = `export const HOMES: Record<string, [number, number]> = `;

const banner =
  "// AUTO-GENERATED by scripts/extract-trips.mjs from reference-v1-app.html.\n" +
  "// Do not hand-edit — re-run the script instead.\n\n";

writeFileSync(
  path.join(root, "src/data/trips.ts"),
  banner + TRIP_TYPE + JSON.stringify(TRIPS, null, 2) + ";\n"
);
writeFileSync(
  path.join(root, "src/data/slots.ts"),
  banner + SLOT_TYPE + JSON.stringify(SLOTS, null, 2) + ";\n"
);
writeFileSync(
  path.join(root, "src/data/homes.ts"),
  banner + HOMES_TYPE + JSON.stringify(HOMES, null, 2) + ";\n"
);

console.log(`TRIPS: ${TRIPS.length} (${expanded} with expanded activities from activityExpansions.json)`);
console.log(`SLOTS: ${SLOTS.length}`);
console.log(`HOMES: ${Object.keys(HOMES).length}`);
console.log("\nSpot-check:");
for (const id of ["rome", "paris", "dublin", "marrakech", "florence"]) {
  const t = TRIPS.find((x) => x.id === id);
  console.log(
    ` ${id}: ${t ? `${t.n}, ${t.c} — g=${t.g} ci=${t.ci} a=${t.a.length} f=${t.f.length}` : "MISSING"}`
  );
}
