// Build-time (not runtime) photo fetcher. Loops the 212 trips in
// src/data/trips.ts, searches Unsplash for a landscape landmark/cityscape
// shot of each, downloads+resizes+compresses it into public/trips/<id>.jpg,
// and records attribution in src/data/tripPhotos.ts. No Unsplash API call
// happens at request time -- the app only ever reads the local files +
// manifest this script produces.
//
// Resumable: safe to stop (Ctrl+C, a rate-limit pause, a crash) and re-run
// later -- it skips any trip that already has both a manifest entry AND a
// downloaded file, and writes the manifest after every single trip so
// interrupting mid-run loses at most the one in-flight trip.
//
// Rate limiting: Unsplash's free "Demo" apps get 50 requests/hour. Each
// trip costs 2 requests (a search + the required "trigger download" ping,
// see below), so a full 212-trip run takes several hours across multiple
// invocations -- this is expected, not a bug. The script reads the real
// X-Ratelimit-Remaining header on every response and stops itself cleanly
// (rather than erroring) once it's nearly exhausted; just re-run the
// script again once the hour resets (or later) to keep going. A small
// fixed delay between trips also keeps requests from bursting even when
// comfortably under the limit.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const ACCESS_KEY = process.env.UNSPLASH_ACCESS_KEY;
if (!ACCESS_KEY) {
  console.error(
    "Missing UNSPLASH_ACCESS_KEY env var.\n" +
      "Create a free app at unsplash.com/developers, copy its Access Key,\n" +
      "and add UNSPLASH_ACCESS_KEY=... to .env.local (never commit it)."
  );
  process.exit(1);
}

const TRIPS_FILE = path.join(root, "src/data/trips.ts");
const MANIFEST_FILE = path.join(root, "src/data/tripPhotos.ts");
const PHOTOS_DIR = path.join(root, "public/trips");

const TARGET_WIDTH = 800;
const JPEG_QUALITY = 78;
const DELAY_MS = 1200; // politeness delay between trips, even when well under the rate limit
const RATE_LIMIT_FLOOR = 3; // stop gracefully once remaining requests get this low

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Same technique scripts/extract-trips.mjs uses on the reference HTML --
 * pull the array-literal source text out of the generated trips.ts and eval
 * it, rather than trying to import a .ts file from a plain .mjs script. */
function loadTrips() {
  const src = readFileSync(TRIPS_FILE, "utf8");
  const marker = "export const TRIPS: Trip[] = [";
  const startIdx = src.indexOf(marker);
  if (startIdx === -1) throw new Error("TRIPS marker not found in trips.ts");
  let slice = src.slice(startIdx + marker.length - 1); // keep the leading '['
  slice = slice.trimEnd();
  if (slice.endsWith(";")) slice = slice.slice(0, -1);
  return new Function(`"use strict"; return (${slice});`)();
}

function loadExistingManifest() {
  if (!existsSync(MANIFEST_FILE)) return {};
  const src = readFileSync(MANIFEST_FILE, "utf8");
  const marker = "export const TRIP_PHOTOS: Record<string, TripPhoto> = ";
  const idx = src.indexOf(marker);
  if (idx === -1) return {};
  let slice = src.slice(idx + marker.length).trimEnd();
  if (slice.endsWith(";")) slice = slice.slice(0, -1);
  return new Function(`"use strict"; return (${slice});`)();
}

function writeManifest(manifest) {
  const ids = Object.keys(manifest).sort();
  const entries = ids
    .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(manifest[id])},`)
    .join("\n");
  const content = `// AUTO-GENERATED by scripts/fetch-photos.mjs. Safe to re-run -- resumable,
// only fetches trips missing an entry here or a downloaded file in
// public/trips/. Do not hand-edit; run the script instead.
export interface TripPhoto {
  file: string;
  photographer: string;
  photographerUrl: string;
  unsplashUrl: string;
}

export const TRIP_PHOTOS: Record<string, TripPhoto> = {
${entries}
};
`;
  writeFileSync(MANIFEST_FILE, content);
}

function rateRemaining(res) {
  const v = res.headers.get("x-ratelimit-remaining");
  return v === null ? -1 : Number(v);
}

async function searchPhoto(query) {
  const url = `https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&orientation=landscape&per_page=1&content_filter=high`;
  const res = await fetch(url, {
    headers: { Authorization: `Client-ID ${ACCESS_KEY}`, "Accept-Version": "v1" },
  });
  const remaining = rateRemaining(res);
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`search failed (${res.status}): ${body.slice(0, 200)}`);
  }
  const data = await res.json();
  return { photo: data.results?.[0] ?? null, remaining };
}

/** Unsplash's API guidelines require this endpoint to be pinged every time
 * a photo is downloaded -- since this script performs exactly one real
 * download per photo (saving it into public/trips/), it's called once,
 * right after that download. */
async function triggerDownload(downloadLocation) {
  const res = await fetch(downloadLocation, { headers: { Authorization: `Client-ID ${ACCESS_KEY}` } });
  if (!res.ok) console.warn(`  trigger-download failed (${res.status}) -- continuing anyway`);
  return rateRemaining(res);
}

async function downloadResizeAndSave(photoUrl, destPath) {
  const res = await fetch(photoUrl);
  if (!res.ok) throw new Error(`image download failed (${res.status})`);
  const buf = Buffer.from(await res.arrayBuffer());
  await sharp(buf).resize({ width: TARGET_WIDTH, withoutEnlargement: true }).jpeg({ quality: JPEG_QUALITY, mozjpeg: true }).toFile(destPath);
}

async function main() {
  const trips = loadTrips();
  const manifest = loadExistingManifest();
  if (!existsSync(PHOTOS_DIR)) mkdirSync(PHOTOS_DIR, { recursive: true });

  let fetched = 0;
  let alreadyDone = 0;

  for (let i = 0; i < trips.length; i++) {
    const trip = trips[i];
    const destFile = path.join(PHOTOS_DIR, `${trip.id}.jpg`);
    const progress = `[${i + 1}/${trips.length}]`;

    if (manifest[trip.id] && existsSync(destFile)) {
      alreadyDone++;
      continue;
    }

    console.log(`${progress} ${trip.n}, ${trip.c} ...`);

    try {
      const { photo, remaining: r1 } = await searchPhoto(`${trip.n} ${trip.c} cityscape landmark`);

      if (!photo) {
        console.warn("  no Unsplash match -- will fall back to the app's placeholder");
        await sleep(DELAY_MS);
        if (r1 >= 0 && r1 <= RATE_LIMIT_FLOOR) {
          console.log(`Rate limit nearly used up (remaining=${r1}) -- stopping for now. Re-run this script later to continue.`);
          break;
        }
        continue;
      }

      await downloadResizeAndSave(photo.urls.regular, destFile);
      const r2 = await triggerDownload(photo.links.download_location);

      manifest[trip.id] = {
        file: `/trips/${trip.id}.jpg`,
        photographer: photo.user.name,
        photographerUrl: `${photo.user.links.html}?utm_source=semesterly&utm_medium=referral`,
        unsplashUrl: `${photo.links.html}?utm_source=semesterly&utm_medium=referral`,
      };
      writeManifest(manifest); // persist immediately -- resumable if this run stops right after
      fetched++;

      const remaining = Math.min(r1 >= 0 ? r1 : Infinity, r2 >= 0 ? r2 : Infinity);
      if (remaining !== Infinity && remaining <= RATE_LIMIT_FLOOR) {
        console.log(`Rate limit nearly used up (remaining=${remaining}) -- stopping for now. Re-run this script later to continue.`);
        break;
      }
    } catch (err) {
      console.error(`  failed: ${err.message} -- skipping, will retry next run`);
    }

    await sleep(DELAY_MS);
  }

  const remainingCount = trips.length - fetched - alreadyDone;
  console.log(`\nDone this run: ${fetched} fetched, ${alreadyDone} already had photos, ${remainingCount} still remaining.`);
  if (remainingCount > 0) console.log("Re-run `npm run fetch-photos` (e.g. next hour) to continue.");
}

main();
