// AUTO-GENERATED by scripts/extract-trips.mjs from reference-v1-app.html.
// Do not hand-edit — re-run the script instead.

export const HOMES: Record<string, [number, number]> = {
  "Prague": [
    50.08,
    14.44
  ],
  "Rome": [
    41.9,
    12.5
  ],
  "Florence": [
    43.77,
    11.26
  ],
  "Milan": [
    45.46,
    9.19
  ],
  "Barcelona": [
    41.39,
    2.17
  ],
  "Madrid": [
    40.42,
    -3.7
  ],
  "Seville": [
    37.39,
    -5.99
  ],
  "Paris": [
    48.86,
    2.35
  ],
  "London": [
    51.51,
    -0.13
  ],
  "Dublin": [
    53.35,
    -6.26
  ],
  "Berlin": [
    52.52,
    13.4
  ],
  "Vienna": [
    48.21,
    16.37
  ],
  "Budapest": [
    47.5,
    19.04
  ],
  "Amsterdam": [
    52.37,
    4.9
  ],
  "Brussels": [
    50.85,
    4.35
  ],
  "Copenhagen": [
    55.68,
    12.57
  ],
  "Stockholm": [
    59.33,
    18.06
  ],
  "Lisbon": [
    38.72,
    -9.14
  ],
  "Porto": [
    41.15,
    -8.61
  ],
  "Athens": [
    37.98,
    23.73
  ]
};
