// AUTO-GENERATED by scripts/fetch-photos.mjs. Safe to re-run -- resumable,
// only fetches trips missing an entry here or a downloaded file in
// public/trips/. Do not hand-edit; run the script instead.
export interface TripPhoto {
  file: string;
  photographer: string;
  photographerUrl: string;
  unsplashUrl: string;
}

export const TRIP_PHOTOS: Record<string, TripPhoto> = {};
